### ISSUE TITLE
Unfriendly error message for undefined variables

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [dciccale/node-htmlprocessor#23]
Getting this when running via the CLI or gulp-htmlprocessor after a fresh install on Windows.

```
C:\Code\FullScreenPokemon>htmlprocessor src\index.html -o lib\index.html
undefined:8
((__t = ( version )) == null ? '' : __t) +
          ^

ReferenceError: version is not defined
    at eval (eval at template (C:\Code\FullScreenPokemon\node_modules\htmlprocessor\node_modules\lodash\dist\lodash.js:6306:22), <anonymous>:8:11)
    at Function.template (C:\Code\FullScreenPokemon\node_modules\htmlprocessor\node_modules\lodash\dist\lodash.js:6312:16)
    at HTMLProcessor.template (C:\Code\FullScreenPokemon\node_modules\htmlprocessor\lib\blocktypes\template.js:8:30)
    at HTMLProcessor._replace (C:\Code\FullScreenPokemon\node_modules\htmlprocessor\lib\htmlprocessor.js:68:45)
    at HTMLProcessor.<anonymous> (C:\Code\FullScreenPokemon\node_modules\htmlprocessor\lib\htmlprocessor.js:91:21)
    at Array.forEach (native)
    at HTMLProcessor._replaceBlocks (C:\Code\FullScreenPokemon\node_modules\htmlprocessor\lib\htmlprocessor.js:86:10)
    at HTMLProcessor.processContent (C:\Code\FullScreenPokemon\node_modules\htmlprocessor\lib\htmlprocessor.js:115:18)
    at HTMLProcessor.process (C:\Code\FullScreenPokemon\node_modules\htmlprocessor\lib\htmlprocessor.js:102:15)
    at C:\Code\FullScreenPokemon\node_modules\htmlprocessor\index.js:43:24
```

Edit 8/12: The cause is that index.html contains a `version` variable that isn't being provided. There should be a friendlier error message about this, yes?

```html
<html>
    <body>
        <% version %>
    </body>
</html>
```

**Comment by dciccale** [comment]
what's the content of `src/index.html`?

**Comment by JoshuaKGoldberg** [comment]
Good catch, removing any reference to `<% version %>` fixes it. Updating the issue now.

**Comment by JoshuaKGoldberg** [comment]
Looking through the source code, this looks like an easy fix. Would you like me to send a PR in a day or two?

**Comment by dciccale** [comment]
right now this shows the default lodash message when parsing a template. we could in theory try cactch that and show a friendlier message.  what do you think?

**Comment by JoshuaKGoldberg** [comment]
I'd have to take a deeper look. Is this something that should be punted to the lodash team to have a friendlier message for,t hen?

**Comment by dciccale** [comment]
unfortunately this is not possible https://github.com/jashkenas/underscore/issues/237

**Comment by dciccale** [comment]
updates?

**Comment by JoshuaKGoldberg** [comment]
> Is this something that should be punted to the lodash team to have a friendlier message for, then?
